In [6]:
import threading
import random
import requests
import browserhistory as bh

def scratch(url):
    extension='https://render-tron.appspot.com/screenshot/'
    render=extension+url
    path='./hello/'+str(random.random())+'.jpg'
    response = requests.get(render, stream=True)
    if response.status_code == 200:
        with open(path, 'wb') as file:
            for chunk in response:
                file.write(chunk)
    return 

def gethome(url):
    end=url.find('/',8,-1)
    url=url[0:end]
    print(url)
    return url


def urlholder():
    dic=bh.get_browserhistory()
    urlno=0
    keys=dic.keys()
    try:
              while dic['firefox'][urlno][0]:
                    url=dic['firefox'][urlno][0]
                    url=gethome(url)
                    #scratch(url)
                    urlno+=1
    except IndexError:
            pass
            return     
        
urlholder()


https://www.google.com
https://www.google.com
https://www.digitalocean.com
https://www.google.com
https://www.google.com
https://www.geeksforgeeks.org
https://www.google.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
https://internshala.com
http://internshala.com
https://blog.internshala.com
http://blog.internshala.com
https://internshala.com
https://internshala.com
https://www.google.com
https://www.youtube.com
http://localhost:8888
https://render-tron.appspot.com
https://render-tron.appspot.com
https://www.geeksforgeeks.org
http://localhost:8888
http://localhost:8888
http://localhost:8888
http://localhost:8888
http://localhost:8888
http://localhost:8888
http://localhost:8888
http://localhost:8888
http://localhost:8888
https://render-tron.appspot.com
https://render-tron.appspot.com
https://d

In [108]:
import browserhistory as bh
dic=bh.get_browserhistory()
ss=dic['firefox']
long=len(ss)
for i in range(0,long):
    link=dic['firefox'][i][0]
    link=str(link)
    end=link.find('/',8,-1)
    url=link[0:end]
    #print(url)
    
import pandas as pd
dataset=pd.DataFrame(dic['firefox'])
dataset.head()
    



def mapinto(link):
    link=str(link)
    linklen=len(link)
    begin=link.find('h',0,linklen)
    end=link.find('/',begin+10,linklen)
    homeurl=link[begin:end]
    return homeurl

def splitter(dates):
    dates=str(dates)
    return  dates.split()
 
    
    
links=dataset.iloc[:,[0]].apply(mapinto,axis=1)

In [109]:
links=pd.DataFrame(links)
dataset=dataset.drop([0],axis=1)
dataset=pd.concat([links,dataset],axis=1)

In [127]:
i=0
while dataset.shape[0]!=i:
        if dataset.loc[[i],[1]].values[0][0]==None:
                pass
        i+=1
        


In [136]:
import numpy as np
dataset.fillna(value="nothing", inplace=True)

In [140]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset.loc[[i],[1]].values[0][0])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
corpus

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()

print(X)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\VickyViper\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
